/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "doovfocmrmpnsfbotoxd"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvb3Zmb2Ntcm1wbnNmYm90b3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzc2MjcxMDAsImV4cCI6MjA5MzIwMzEwMH0.81FibrgNRtDdLVjj4ip-99E1zfoYPILepchO8EX-YOE"
